eventStreams:
  buildEvents:
    plugin: Kafka
    config:
      consumerTopic: build_events
      groupId: notifier
      clientId: probo-notifier
      brokers:
        - localhost:9092

assets:
  url: "http://localhost:3070"
  token: "API token here"
