eventStreams:
  buildEvents:
    plugin: Kafka
    config:
      topic: build_events
      group: notifier
      version: 1
      streamOptions:
        highWaterMark: 0

assets:
  url: "http://localhost:3070"
  token: "API token here"
