apiServerHost: localhost
apiServerPort: 3039
eventStreams:
  buildEvents:
    plugin: Kafka
    config:
      topic: build_events
      group: notifier
      version: 1
      streamOptions:
        highWaterMark: 0
